### ISSUE TITLE
spike correction should be ADC subtraction instead of the interpolation

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/ctapipe_io_lst#122]
Just let me report:
If predicted spikes are located at the pulse peak position, spike correction reduces the pulse height.
![pulse_with_spike](https://user-images.githubusercontent.com/31307823/100614775-00e4cd00-335a-11eb-939f-a1f1c5f48b93.png)

As @tysaito2008 explained in the reco meeting, Tomohiko @toka2018 is studying the spike feature and implementing the new spike correction (ADC subtraction) into lstchain.

**Comment by maxnoe** [comment]
![run2965_event49751_pixel190_highgain](https://user-images.githubusercontent.com/5488440/142251969-dd4a8d0f-3a46-4fa6-b2aa-0ceec9eaf2cb.png)
![run2965_event45628_pixel612_highgain](https://user-images.githubusercontent.com/5488440/142251975-68936fce-9c87-4d65-8506-1fb812f1779d.png)


Implemented now in #96 together with the PR for the new drs4 pedestal tool that also calculates spike heights
