### ISSUE TITLE
Properly tag pedestal events before July 2020

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/ctapipe_io_lst#123]
I realized that we can easily solve the issue of mis-tagged interleaved pedestal events before July 2020, and those on the 20201217 - 20201221 nights,  which prevents us from applying the "pedestal cleaning" to those data. There is a lot of good data (Crab for example) that will benefit from this.

The intervals at which the interleaved pedestals arrive are very regular, better than ~usec precision. Therefore it is enough to comb the dragon_times  series of a subrun to find the combination of period and phase which maximizes the number of regularly spaced events: 

![image](https://user-images.githubusercontent.com/14164282/142665902-643580a5-6af4-43cc-87fc-9adac95043d4.png)

This is for a subrun and I did it ala brute force, scanning the periods in 20 steps of 0.1 usec and then scanning the phase in ns steps (despite which it is pretty fast, a couple of seconds)

The resulting tag is ok, save for the negligible contamination of showers which fall there. This is a comparison of the distribution of pixel charges for the pedestals found this way and those from the pedestal tag in Nov'2020 subrun with proper tagging:

![image](https://user-images.githubusercontent.com/14164282/142667558-e46b80b4-71c0-4135-b97e-fac07d27ed5f.png)

This is for an old  subrun with no tagging available:
![image](https://user-images.githubusercontent.com/14164282/142667802-f6efca75-1ef9-410b-a964-4ded232da0fe.png)

The window to select the pedestals is 1-microsec wide, which means we should have a contamination of O(1e-2) cosmics per second, compared to 50 /s  genuine pedestals, so things should work fine in the analysis of interleaveds.

The question @maxnoe is where to integrate this. We need to have the full list of times, so it requires a "first pass" over the whole run. Should this be an option in the LST event source, or should we implement this at a higher level, in lstchain?

**Comment by moralejo** [comment]
Obviously doing it in lstchain is not such a good idea with the convergence with the ctapipe stage1 in mind...

**Comment by moralejo** [comment]
Actually, since there is the danger of some non-pedestal events falling by chance in the "windows" of pedestals, it would be convenient to exclude a few of the "most suspicious" events from the output list of pedestals event_id's, and this is more easily done if the check is done on DL1 files. So I am for the option of finding the event_id's from the existing DL1 (once and forever) and then make the event source read those lists if found together with the raw data.

**Comment by moralejo** [comment]
Implemented a finder in https://github.com/cta-observatory/cta-lstchain/pull/798

**Comment by moralejo** [comment]
@maxnoe is it ok if I proceed with making a function to read in the hdf5 files produced by the script in https://github.com/cta-observatory/cta-lstchain/pull/798 (in case they are found in the same directory as the raw file) and tag the pedestal events, or do you see any drawback?

**Comment by maxnoe** [comment]
@moralejo I think this should go into the `real/monitoring` data tree, right @FrancaCassol?

And I would prefer a `Path` option, not some automatic checking to be able to properly test this also in the non-standard directory tree in the cluster.

**Comment by moralejo** [comment]
Ok, I'll wait for @FrancaCassol's opinion on the location.
I just wanted to make this as transparent as possible for LSTOSA, so they don't have to care about run ranges or anything. But indeed, we can set a Path option with the default in the calibration tree

**Comment by FrancaCassol** [comment]
Hi @moralejo and @maxnoe,

actually, it seems to me that this concerns more the data tree than the monitoring tree, in fact this is an information supposed to be in the data, that is unfortunately missing. Since it will be available only after a first DL1 production, I would put it inside the DL1 tree:
/fefs/aswg/data/real/DL1/[date]/pedestal_index

**Comment by moralejo** [comment]
I don't think it should be the DL1. Once produced it will be read together with the raw data, so I would place it under /R0/pedestal_index.

**Comment by FrancaCassol** [comment]
Personally I would not mix data coming from EvB with data produced the day after.
Also the R0 directory is at the moment a link to /fefs/onsite/data/

If you do not want them in DL1, then better to put them in the monitoring directory as suggested by @maxnoe, even if they are not monitoring. 
By the way, I am facing a similar problem with the level B pixel calibration (produced from the DL1 data), should we perhaps create a PixelCalibration/level_A and a PixelCalibration/level_B directory?

**Comment by moralejo** [comment]
I addressed the pending suggestions in https://github.com/cta-observatory/cta-lstchain/pull/798

As to where the files should go, how about 
`/fefs/aswg/data/real/Aux/pedestal_event_ids/YYYYMMDD` 
? 
I will take care of filling it for the relevant dates as soon as the PR above is merged.

Now we need that the event source (through an option in the json file) reads in the hdf5 files produced by the pedestal finder (they have a single table called interleaved_pedestal_ids with a single column 'event_id'), and tags the given event id's as pedestals in "event_type", disregarding the values of the 'trigger type' for those events. To make things easier for LSTOSA I think we could activate this option by default, and (obviously) apply it only when the corresponding pedestal_ids file is found. I will make sure that all the relevant nights are present in the directory.

I insist that this is quite important because it will allow us to perform a better analysis of the first LST1 Crab season, and everything else taken before July 2020.

@maxnoe could you make the necessary changes in the event source?

**Comment by maxnoe** [comment]
This was implemented in https://github.com/cta-observatory/ctapipe_io_lst/pull/129
