### ISSUE TITLE
Check if events already flagged as FF fulfill the condition in the heuristic method 

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/ctapipe_io_lst#124]
https://github.com/cta-observatory/ctapipe_io_lst/blob/490a4bbebbb03747caa15c2dc739c01149487341/ctapipe_io_lst/__init__.py#L577

We have realized (with @FrancaCassol) that since June 1st (following TIB firmware update from v2 to v3) some non-flatfield events are incorrectly tagged as flatfield in ucts_trigger_type

The tag_flatfield_events function flags very bright events as FF, but it does not check whether events which already have the tag really look like FF events or not. If it did, it could set those event_types to unknown, and that would save some trouble downstream. @maxnoe, does that look reasonable?

**Comment by moralejo** [comment]
Besides, we could provide some warning when an inconsistency of this type is spotted.

**Comment by maxnoe** [comment]
Yes, sounds reasonable. Did you also open a redmine issue witht he TIB guys so the root cause can be investigated/fixed?

**Comment by moralejo** [comment]
I told Juan Abel Barrio, he said there is already a new version installed, but we did not take any sky data after that. He asked us to check again as soon as there is data. But it should be a dedicated check, obviously letting the events through and seeing that the interleaved calibration is spoiled is not the best way, because then you cannot spot other issues (and analysis may be affected downstream).
I have introduced a check in the DL1 check code of whether FF tagged interleaved events  really looked like they should, and I am now just skipping them, but I will add a warning.

**Comment by maxnoe** [comment]
Do you have an example obs_id / event_id?

**Comment by moralejo** [comment]
Run 4897
event id 26157

**Comment by moralejo** [comment]
Why am I not getting notifications for this thread? (I am subscribed to all notifications) Is it ok for you @maxnoe ?
