### ISSUE TITLE
fits file is not closed in is_compatible

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe_io_lst#167]
https://github.com/cta-observatory/ctapipe_io_lst/blob/18d4cee27d5fb6bfb26ef9bf3ed47c695fa2a856/src/ctapipe_io_lst/__init__.py#L514

There is no coressponding fits.close() or context manager.  This should leak file handles.  Perhaps use `fits.get_header()` instead?

**Comment by maxnoe** [comment]
It also might raise if the `2` extension is not there.... thanks
