### ISSUE TITLE
processing of pixel_status?

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/ctapipe_io_lst#177]
https://github.com/cta-observatory/ctapipe_io_lst/blob/89906059ddcb2d8277ad5678bd2cd93cc3120e96/src/ctapipe_io_lst/__init__.py#L120

Should this be
return (pixel_status & 0b1110) >> 1  ?

It seems to me that a pixel_status = 0b0010,  ~~which means only high gain is stored~~, should return non-zero 
As of now, that status results in a pixel being tagged among hardware_failing_pixels in the monitoring container.

**Comment by maxnoe** [comment]
The channel info bits are the bits 2 and 3 in the data model, they encode if high gain and low gain were read out respectively:

![pixel_trigger_status](https://github.com/cta-observatory/ctapipe_io_lst/assets/5488440/cc58bf3d-03ec-4581-ac35-5633971a276d)


So anding with `b(0000_)1100` will extract only those two bits, shifting to the right by two just makes it easier to check the values as they will be 0, 1, 2 (10), or 3 (11) (equivalent to nothing read out, high gain readout, low gain readout, both gains readout).

**Comment by moralejo** [comment]
You are right, I got the bits wrong, sorry!
