### ISSUE TITLE
`event_type` set to unknown (255) with `ctapipe v0.20.0`

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/ctapipe_io_lst#204]
When writing interleaved calibration events using `ctapipe v0.20.0`, the `event_type` is set to `255`, i.e. unknown type.

<img width="898" alt="Screenshot 2023-11-21 at 11 44 02" src="https://github.com/cta-observatory/ctapipe_io_lst/assets/37835610/4deda265-7b9b-41ee-b1bd-2da871e1ef37">

**Comment by maxnoe** [comment]
@TjarkMiener right... I didn't anticipate someone would try to read the old EVBv5 data with a ctapipe version not used in lstchain

> For all events? Or just some of them?

All, the field is simply not filled and then the default takes effect. Note that the information is correctly filled in the place where it used to be, ie.e. `dl1.event.subarray.trigger` but not where we added the new field in ctapipe 0.20.

Also, please not that this is `ctapipe_io_lst`, but of course you are welcome to help :)

**Comment by Tobychev** [comment]
> Also, please not that this is ctapipe_io_lst, but of course you are welcome to help :)

Oh no, I've been bamboozled!

**Comment by TjarkMiener** [comment]
Yes, my motivation was to write some interleaved calibration following the CTAO DL0 data format of ctapipe v0.20.0, which is related to [lstchain-#1176](https://github.com/cta-observatory/cta-lstchain/issues/1176). I'd be happy to help!
