### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/ctapipe_io_lst#24]
There are two `version.py` (main dir and in `ctapipe_io_lst` dir) and the version is not  really recognized.
When installing with  `pip install https://github.com/cta-observatory/ctapipe_io_lst/archive/v0.4.1.zip` the version  is `unknown` and when installing with `pip install .` the version is `0.1.post53+git63772f7`

**Comment by MaxNoe** [comment]
Ah, yes. This is an issue I forgot.

The tar/zip ball provided by github does neither contain the `__version__`  written by the version script nor the necessary git information to create it.

This would be solvable by uploading the sdist build by travos either to github releases or directly to pypi

**Comment by MaxNoe** [comment]
Same behaviuour btw. for ctapipe

**Comment by rlopezcoto** [comment]
this is what I was reporting this morning by e-mail. It is the same when you install it using the [environment file from lstchain](https://github.com/cta-observatory/cta-lstchain/blob/master/environment.yml), which is probably the most usual way that this repo is going to be installed.
@vuillaut if you install if with `pip install -e .` the version reported is the right one, right?

**Comment by vuillaut** [comment]
Hi @MaxNoe .
Is there a way to fix this?

**Comment by MaxNoe** [comment]
Yes, upload to pypi would be the simplest one. I can add the travis config.

To get rid of the duplication, we'd need to remove the imports of subpackages in `__init__`

**Comment by rlopezcoto** [comment]
as you know, we have the same issue in [cta-lstchain](https://github.com/cta-observatory/cta-lstchain), anybody who works out the solution, could also implement it there, please?

**Comment by maxnoe** [comment]
Fixed by using setuptools scm
