### ISSUE TITLE
EventSource.subarray must be a property

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe_io_lst#28]
Currently the lst event source deviates from the API of the baseclass, which makes it impossible to use in programs that just use the generic `EventSource` and rely on a common API.

**Comment by FrancaCassol** [comment]
Hi @MaxNoe,
yes, I think the implementation  of the subarray was not orthodox,  could you indicate a source with the correct API, to take as example?

**Comment by MaxNoe** [comment]
`ctapipe.io.EventSource` is the abstract baseclass, which has the API we need to implement.

`.subarray` needs to be a simple property, so one can do:

```
event_source = ...
print(event_source.subarry)
```
