### ISSUE TITLE
Update protozfitsreader?

### ISSUE THREAD

**Issue by rlopezcoto** [cta-observatory/ctapipe_io_lst#31]
As suggested by @MaxNoe in [ctapipe_io_lst](https://github.com/cta-observatory/ctapipe_io_lst/pull/22), protozfitsreader is already in an [older version](https://github.com/cta-sst-1m/protozfitsreader/releases/tag/1.5.0) than the one we are using

**Comment by rlopezcoto** [comment]
Thanks @MaxNoe! Better like this

**Comment by maxnoe** [comment]
We currently use the latest release (and will update soon to 2.0 as soon as we can elease this)
