### ISSUE TITLE
Add `protozfits` in the requirements

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/ctapipe_io_lst#4]

**Comment by vuillaut** [comment]
Hi @FrancaCassol 
I will need this to fix `lstchain` travis build.

**Comment by MaxNoe** [comment]
It is in the requirements (setup.py `install_requires`), the problem is, that it is not pip installable and has thus be installed manually.

**Comment by vuillaut** [comment]
Isn't it pip installable with
```
pip install https://github.com/cta-sst-1m/protozfitsreader/archive/v1.4.2.tar.gz
```
?

**Comment by MaxNoe** [comment]
Sorry, clarified my comment a second later
