### ISSUE TITLE
Apply R0 → DL0 calibration in event source

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe_io_lst#43]
This is needed to make the event source compatible with the data model, e.g. with the `ctapipe-stage1-process` tool.

**Comment by vuillaut** [comment]
Did not see this one  before starting the discussion in #42

**Comment by MaxNoe** [comment]
Right now, only R1 would be required by ctapipe to work, see https://github.com/cta-observatory/ctapipe/pull/1387#issuecomment-660029211

**Comment by MaxNoe** [comment]
First draft here #44
