### ISSUE TITLE
Fill `event.trigger.time` field

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/ctapipe_io_lst#46]
Was this previously done by ctapipe?

**Comment by MaxNoe** [comment]
No, ctapipe does not know anything about lat specific fields

**Comment by vuillaut** [comment]
Sorry I wasn't clear enough.
In ctapipe 0.7 there was an `event.trig.gps_time` field, that is now `event.trigger.time`.
As this is an event level information, I suppose it is filled at the array level and not telescope level.
But I cannot find where 😅

**Comment by vuillaut** [comment]
That's because it has never actually been filled

**Comment by vuillaut** [comment]
Should be an astropy Time object
```
In [13]: event.trigger.time                                                                                                                                                                                                                                                  
Out[13]: <Time object: scale='utc' format='unix' value=1408549473.035597>

```
