### ISSUE TITLE
Support for data taken with switched off modules

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe_io_lst#60]
New event builder version (from tonight onwards) will not include data for switched off pixels / modules.

We need to support this.

Decisions during today's LST telcon:

* The source should still produce CameraGeometry / waveforms / etc. that has all 265 modules / 1855 pixels

Open questions:

- [ ] Do `expected_modules_id` / `expected_pixels_id` contain switched off modules? Almost certainly no.
- [ ] Do the pixel_status / module_status contain the switched off modules? I guess yes?
- [ ] Do the `first_capacitors` contain the switced off modules? I guess no.
- [ ] Create test data file as soon as data like this is available
- [ ] Fill value? I would propose `np.float32(nan)` where waveform is a float and `np.iinfo(np.uint16).max` where it is an integer.

**Comment by morcuended** [comment]
Concerning the last point, the current real R0 files should be still valid, right? Do we just need another test file taken with an off module?
What about R0 files to create drs4 and calibrations files as well? (although this last part should be just for lstchain not for ctapipe_io_lst) I guess

**Comment by maxnoe** [comment]
> Concerning the last point, the current real R0 files should be still valid, right? Do we just need another test file taken with an off module?

Yes.

**Comment by rlopezcoto** [comment]
was there any test data uploaded with an off module?

**Comment by maxnoe** [comment]
Yes

**Comment by rlopezcoto** [comment]
> Yes, see the corresponding unit test

sorry, which ones? at the moment I can only find:
https://github.com/cta-observatory/cta-lstchain/blob/d9b050646cb554e005c65295f72b75c2be5ea334/lstchain/tests/test_lstchain.py#L15-L22

do you think it would be a good idea to keep a text file with all the data that are available for testing the software?

**Comment by maxnoe** [comment]
https://github.com/cta-observatory/ctapipe_io_lst/blob/a28809b595708a295d50ace067865539a074b57c/ctapipe_io_lst/tests/test_calib.py#L18

**Comment by rlopezcoto** [comment]
thanks!
