### ISSUE TITLE
Read LST data ValueError: Timestamp

### ISSUE THREAD

**Issue by pawel21** [cta-observatory/ctapipe_io_lst#69]
One more problem,

When I tried read data:
```
path1 = "/media/pawel1/ADATA HD330/20210215/LST-1.1.Run03670.0000.fits.fz" 
path2 = "/media/pawel1/ADATA HD330/20191123/LST-1.1.Run01610.0000.fits.fz" 
reader = LSTEventSource(input_url=path1, max_events=10) 
for ev in reader: 
    pass 
```
I got error: 
`ValueError: Timestamp reference should be extracted from first event but UCTS not available`

**Comment by maxnoe** [comment]
Yes, this is expected for runs with missing UCTS.

You can need to pass `fill_timestamp=False` for such runs.
