### ISSUE TITLE
Behaviour for missing UCTS and/or TIB

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe_io_lst#71]
It seems there are data files where UCTS and dragon counters are available but not TIB.
Currently the `EventTimeCalculator` only supports values for all 4 options.

Should we support only giving counter0 / ucts_t0 for tib OR dragon?

#### Assumptions:

Please correct any wrong assumptions:

* A precise absolute timestamp is only possible through the UCTS timestamp
* The most precise timestamp is the combination of the relative dragon counter with using a UCTS timestamp / dragon counter combination as reference.
* There are data files with missing UCTS
* There are data files with missing TIB
* There are data files with missing UCTS and missing TIB
* Data files with missing dragon counters do not exist / are anyways not analyzable
* Using `CameraConfiguration.date` as reference for dragon / TIB results in timestamps wrong by at least several seconds up to > 120 seconds since it is a run start timestamp not timestamp of the first event.

#### UCTS missing

* No absolute timestamp possible.
* Currently raises an error, can be mitigated by using `LSTEventSource.fill_timestamp = False`
* Should we not raise an error and just fill the invalid time marker?

#### TIB missing
* Only real side effect is that we cannot use TIB trigger type as fallback for UCTS when a jump happens.
* But currently, we require setting tib counters, even when we do not use TIB for the timestamp. Adressed in #72

**Comment by FrancaCassol** [comment]
At least till the data are so unstable, I would say 'yes'

**Comment by maxnoe** [comment]
@FrancaCassol @moralejo I added some more details, please check and comment.

**Comment by moralejo** [comment]
The assumptions seem correct to me. 

Let me mention that I am not very confident about the way the night summary determines the dragon counter for the first event: I think it makes a distribution for all modules and takes the mode. @morcuended can correct me, if that is not the case.  Then, in building the Dragon timestamp we actually take the counter from a specific module. This may result is differences of some 100 ns if the module turns out not to have the same counter for the first event as the majority of modules. I am afraid this is what has led Yoshiki to see a jump of 300 ns in the time difference between MAGIC and LST1 between two consecutive runs (reported on the LST analysis call, see page 6 of https://indico.cta-observatory.org/event/3309/contributions/27547/attachments/18864/25821/lst_reco_20210215.pdf)

> #### Szenarios
> #### UCTS missing
> * No absolute timestamp possible.
> * Currently raises an error, can be mitigated by using `LSTEventSource.fill_timestamp = False`
> * Should we not raise an error and just fill the invalid time marker?

I think we should, yes. Some (ok, few) of the later analyses may not need time at all, so why not to process the data?

> 
> #### TIB missing
> * Only real side effect is that we cannot use TIB trigger type as fallback for UCTS when a jump happens.
> * But currently, we require setting tib counters, even when we do not use TIB for the timestamp. Adressed in #72

Correct, no major problem there, just single events without valid trigger type.

**Comment by moralejo** [comment]
> Let me mention that I am not very confident about the way the night summary determines the dragon counter for the first event: I think it makes a distribution for all modules and takes the mode. @morcuended can correct me, if that is not the case. Then, in building the Dragon timestamp we actually take the counter from a specific module. This may result is differences of some 100 ns if the module turns out not to have the same counter for the first event as the majority of modules. 

Actually we could make LSTOSA independent of the NightSummary, getting the needed values directly with lstchain from subrun 1. Was there any problem for doing so, @morcuended @FrancaCassol ?

**Comment by maxnoe** [comment]
> 100 ns

Please note that the timestamps we are providing here are not precise to that level. Using a single float64 gets you only to ~300 ns precision.

**Comment by maxnoe** [comment]
> Actually we could make LSTOSA independent of the NightSummary

The whole point of this night summary is providing the counter values, right? There is no other information in it.

**Comment by moralejo** [comment]
> > 100 ns
> 
> Please note that the timestamps we are providing here are not precise to that level. Using a single float64 gets you only to ~300 ns precision.

Is that the case? I wouldn't say so, judging e.g. from Yukiho's LST1 vs MAGIC plots.

**Comment by moralejo** [comment]
> > Actually we could make LSTOSA independent of the NightSummary
> 
> The whole point of this night summary is providing the counter values, right? There is no other information in it.

But perhaps Isidro's low-level data check uses them somewhere else, I don't know.
What definitely worries me is the difference between how the 1st event reference is calculated and how we later calculate the event-wise timestamp.

**Comment by morcuended** [comment]
> But perhaps Isidro's low-level data check uses them somewhere else, I don't know.
> What definitely worries me is the difference between how the 1st event reference is calculated and how we later calculate the event-wise timestamp.

NightSummary files were created specifically for LSTOSA and we extract timestamps, counters and the number of subruns.

**Comment by morcuended** [comment]
> Actually we could make LSTOSA independent of the NightSummary, getting the needed values directly with lstchain from subrun 1. Was there any problem for doing so, @morcuended @FrancaCassol ?

Not a problem for us. This was one of the possibilities back then when we struggled with this problem but we decided to do it with pre-calculated values in the night summaries.

If we want to do it with lstchain I guess we need to always open the first subrun file and get the initial valid timestamps and corresponding counters for every subrun, right?

**Comment by morcuended** [comment]
> UCTS missing
> No absolute timestamp possible.
> Currently raises an error, can be mitigated by using LSTEventSource.fill_timestamp = False
> Should we not raise an error and just fill the invalid time marker?

I'd add here, that pointing being interpolated in this case would not be correct.

**Comment by maxnoe** [comment]
I'd say pointing shouldn't be interpolated for that. So probably we need to check for the invalid time in the pointing interpolator

**Comment by maxnoe** [comment]
> Is that the case? I wouldn't say so, judging e.g. from Yukiho's LST1 vs MAGIC plots.

Yes, a single float64 storing mjd or unix timestamps cannot be more precise. Since we create a single float64 holding the unix_tai format before giving it to astropy time (which can be more precise by using two floats) we are limited to that precision.
So I am a bit surprised you say we have better precision *for single events*.

If you are talking about something like the mean over many events, that's of course different.

**Comment by moralejo** [comment]
> > Is that the case? I wouldn't say so, judging e.g. from Yukiho's LST1 vs MAGIC plots.
> 
> Yes, a single float64 storing mjd or unix timestamps cannot be more precise. Since we create a single float64 holding the unix_tai format before giving it to astropy time (which can be more precise by using two floats) we are limited to that precision.
> So I am a bit surprised you say we have better precision _for single events_.
> 
> If you are talking about something like the mean over many events, that's of course different.

Yes, you are right, it is 100 ns.  In Yoshiki 's slide the y-axis is the average delay which maximizes coincidences (over many events). 
Still, I think the reason for the jump he observes is an error in the building of the dragon timestamp for the reason discussed above.

**Comment by maxnoe** [comment]
We discussed in slack, that using TIB for the timestamp is not necessary, since dragon is always available and more precise.

We also decided that we should add the option back to allow using `event.lst.svc.date` (e.g. the start of run timestamp) as reference when no dragon reference values are available.

**Comment by maxnoe** [comment]
For now implemented in #72
