### ISSUE TITLE
Files without Events table

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe_io_lst#78]
As reported by @moralejo here: https://github.com/cta-observatory/cta-lstchain/pull/614#issuecomment-790820220  there are some files that lack the Events table completely.

Currently, the event source for those runs has `is_compatible(path) == False` and raises an Error when directly opening.

Should we be able to open these files and just have 0 Events? Or is raising an error / not being compatible ok?

**Comment by rlopezcoto** [comment]
What is the containment of those files if they do do not contain Events?
I would say that if there is something useful inside that may be needed to be accessed, then a warning could be raised, otherwise an error is fine.

**Comment by maxnoe** [comment]
Only the CameraConfiguration table

**Comment by rlopezcoto** [comment]
if nobody is interested in the `CameraConfiguration` table of a file that do not contain events, I'd say it is fine to raise an error

**Comment by maxnoe** [comment]
With the restructuring in #160, this got adressed.
