### ISSUE TITLE
CDTS info has wrong dtypes

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe_io_lst#80]
```
    ('address', np.float32), 
    ('event_counter', np.float32),
    ('busy_counter', np.float32),
    ('pps_counter', np.float32),

```

These should clearly be ints and the values are nonsensical right now due to this.

@FrancaCassol do you know where to get the correct dtypes from?

**Comment by FrancaCassol** [comment]
It is described in the "ICD of Event-Builder « iDAQ »", but I do not know if this is the most recent version 
[LSTMST-ICD-20191206.pdf](https://github.com/cta-observatory/ctapipe_io_lst/files/6090288/LSTMST-ICD-20191206.pdf)

**Comment by FrancaCassol** [comment]
page 12
